; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sat Apr 17 2021 17:22:42 GMT+0100 (British Summer Time)

