; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sat Apr 17 2021 17:22:42 GMT+0100 (British Summer Time)
; Wait for set temperatures to be reached
M116 P0

